"""empty message

Revision ID: 2db920aa0226
Revises: 4a695646aa5f
Create Date: 2020-10-24 00:53:19.909666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db920aa0226'
down_revision = '4a695646aa5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'movie_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('actors', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('movies', 'title',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'title',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('actors', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('actors', 'movie_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###
